"""empty message

Revision ID: a64d6acc64e0
Revises: 8532d6be8948
Create Date: 2018-10-08 09:24:53.645606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64d6acc64e0'
down_revision = '8532d6be8948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklists')
    # ### end Alembic commands ###
